name: flutterapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons asset.font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  percent_indicator: ^2.1.5
  curved_navigation_bar: ^0.3.3
  google_fonts: ^0.3.5
  double_back_to_close_app: ^1.2.0
  flutter_keyboard_visibility: ^3.2.1
  flutter_auth_buttons: any
  introduction_screen: ^1.0.7
  simple_animations: ^1.3.3
  flutter_typeahead: ^1.8.5
  font_awesome_flutter: ^8.8.1
  awesome_dialog: ^0.1.3
  pin_entry_text_field: ^0.1.4
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  fa_stepper: ^0.0.2
  intl: ^0.15.6
  sliding_up_panel: ^1.0.2
  datetime_picker_formfield: ^1.0.0
  gender_selection: ^1.0.0
  expandable_bottom_sheet: ^0.2.1+1
  smooth_star_rating: ^1.1.1
  animated_size_and_fade: ^1.1.1
  auto_size_text: ^2.1.0
  mixed_collection: ^0.1.5
  shared_preferences: ^0.5.8
  after_layout: ^1.0.7+2
  modal_progress_hud: ^0.1.3
  fluttertoast: ^7.0.1
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6
  flutter_animation_progress_bar: ^1.0.0

  #flutter_svg: ^0.17.4
  #animations: ^1.1.0 

  rflutter_alert: ^1.0.3

  numeric_keyboard: ^1.0.0

  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  - assets/google_logo.png
  - assets/fblogo.jpg
  - assets/googlelogo.png
  - assets/eclipse_loading.gif
  - assets/images/
  - assets/icons/
  - images/dp.jpeg
  - images/1.jpg
  - images/2.jpg
  - images/3.jpg
  - images/4.jpg
  
  
  
  

flutter:


  uses-material-design: true

  assets:
    - assets/
    - images/dp.jpeg
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/camera.png
    - images/camera1.jpg
    - images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 400

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the asset.font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the asset.font. For
  # example:
  #fonts:
  #   - family: Schyler
  #    fonts:
  #      - asset: fonts/Schuyler.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
